# Generated by Django 5.0.4 on 2024-05-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_slotregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotregistration',
            name='Arrivaltime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='slotregistration',
            name='Departuretime',
            field=models.DateTimeField(),
        ),
    ]
