# Generated by Django 5.0.4 on 2024-05-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_slotregistration_arrivaltime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000)),
                ('starthours', models.DateTimeField()),
                ('endhours', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('Datetime', models.DateTimeField()),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='SlotRegistration',
        ),
    ]
