# Generated by Django 5.0.4 on 2024-05-24 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_parkingspace_delete_slotregistration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot_reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starthours', models.DateTimeField()),
                ('endhours', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('transaction_id', models.CharField(max_length=1000, unique=True)),
                ('ParkingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.parkingspace')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
